package exception;

public class ExceptionDemo {
	public static void main(String[] args) {
		try {
			int result=divide(10,0);
			System.out.println(result);
		}
		  catch(ArithmeticException e) {
			  System.out.println("cautch Exception "+e.getMessage());
		  }
		finally {
			System.out.println("finally block must be executed");
		
		}
	}
	
		public static int divide(int a,int b)throws ArithmeticException  {
			
			if(b==0)
				{
				throw new ArithmeticException("divide by zero");
				}
			return a/b;
			
		
	
		}

}
